import { useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import WhyBookOnePos from "../components/WhyBookOnePos";
import WhyBookOnePosNav from "../components/WhyBookOnePosNav";
import TrustedCard from "../components/TrustedCard";
import { AiOutlineDown } from "react-icons/ai";
import { createClient } from "contentful";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res1 = await client.getEntries({ content_type: "homePage" });
  const res2 = await client.getEntries({
    content_type: "homePageTrustedClients",
  });
  const res3 = await client.getEntries({ content_type: "homePageTopPartHero" });
  const res4 = await client.getEntries({ content_type: "homePageOutletType" });

  return {
    props: {
      test1: res1.items,
      test2: res2.items,
      test3: res3.items,
      test4: res4.items,
    },
  };
}

export default function Home(props) {
  // console.log(props.test1);
  // console.log(props.test2);
  // console.log(props.test3);
  console.log(props.test4);

  const [passedId, setPassedId] = useState(props.test1[0].sys.id);
  const [title, setTitle] = useState(props.test1[0].fields.title);
  const [content, setContent] = useState(
    documentToReactComponents(props.test1[0].fields.content)
  );
  const [image, setImage] = useState(
    props.test1[0].fields.image.fields.file.url
  );
  const [srNo, setSrNo] = useState(1);

  // console.log(passedId);

  return (
    <div>
      <Head>
        <title>bookone-POS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heroContainer}>
        <div className={styles.leftSection}>
          <div className={styles.heroText}>
            <h1 className={styles.Text1}>
              {props.test3[0].fields.title}
              <span
                className={styles.gradientText}
                style={{ marginLeft: "15px", marginRight: "15px" }}
              >
                {props.test3[0].fields.title2}
              </span>{" "}
              {props.test3[0].fields.title3}
            </h1>
            <div className={styles.Text2}>
              {documentToReactComponents(props.test3[0].fields.description)}
            </div>
            <button className={styles.heroTextButton}>
              {props.test3[0].fields.demoButton}
            </button>
          </div>

          <div className={styles.polygon}>
            <img className={styles.polygonArrow} src="/heroArrow.svg" alt="" />
          </div>
        </div>

        <div className={styles.signUpContainer}>
          <div className={styles.signUpImg}>
            <img src="/Sign-Up.jpg" alt="" />
          </div>
        </div>
      </div>

      <div className={styles.whyBigContainer}>
        <div className={styles.whyContainer}>
          <h3 className={styles.whyHeading}>Why BookOne POS?</h3>

          <div className={styles.tabContainer}>
            {props.test1.map((feature, index) => (
              <WhyBookOnePosNav
                key={feature.sys.id}
                feature={feature}
                index={index}
                passedId={setPassedId}
                setTitle={setTitle}
                setContent={setContent}
                setImage={setImage}
                setSrNo={setSrNo}
              />
            ))}
          </div>

          <WhyBookOnePos
            title={title}
            content={content}
            image={image}
            srNo={srNo}
          />
        </div>

        <div className={styles.trustedRestContainer}>
          <h6>
            Trusted by <span>500+</span> Restaurants Partners
          </h6>
          <div className={styles.cards}>
            {props.test2.map((card) => (
              <TrustedCard key={card.sys.id} card={card} />
            ))}
          </div>
          <div className={styles.showMore}>
            <button>
              Show More <AiOutlineDown style={{ paddingTop: "5px" }} />
            </button>
          </div>
        </div>
        <div className={styles.outletTypeContainer}>
          <div className={styles.outletType}>
            <h4>{props.test4[0].fields.title}</h4>
            <div>
              {documentToReactComponents(props.test4[0].fields.description)}
            </div>
            <div className={styles.outletCards}>
              <div className={styles.outletCard}>
                {/* Content in contentful not updated */}
              </div>
              <div className={styles.outletCard}>
                {/* Content in contentful not updated */}
              </div>
              <div className={styles.outletCard}>
                {/* Content in contentful not updated */}
              </div>
              <div className={styles.outletCard}>
                {/* Content in contentful not updated */}
              </div>
              <div className={styles.outletCard}>
                {/* Content in contentful not updated */}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
